#Java
#Checkout,Codescan,QualityCheck,Build,UploadArtifacts and Deploy To Webapp
name: $(build.sourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
trigger: 
  - master
variables:
  sonarServiceConnection: 'sonar-ahold'
  sonarProjectKey: 'jpetstore'
  sonarProjectName: 'jpetstore'
  sonarSources: '.'
  sonarJavaSource: '.'
  sonarJavaBinaries: '.'
  sonar.junit.reportsPath: 'target/surefire-reports'
  sonar.surefire.reportsPath: 'target/surefire-reports'
  sonar.jacoco.reportPath: 'target/jacoco.exec'
  sonar.binaries: 'target/classes'
  sonar.java.coveragePlugin: 'jacoco'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  #Build Artifacts
  publishesArtifactsPath: '/home/vsts/work/1/s/target/'
  artifactsPath: '/home/vsts/work/1/s/target/jpetstore.war'
  artifactRepoName: 'jpetstore'
  artifactVersionType: 'patch'
  webServer: 'java-sample-demo11'
  azureServiceConnectionId: 'ahold-poc-demo'
  azureArtifactName: 'jpetstore'
  azureFeedPublishName: '765878f8-c954-450c-9d10-10f7effa2b3c'
stages:
- stage: JavaBuildPipeline
  displayName: Java CI CD Build Pipeline
  jobs:  
  - job: JavaBuildPipeline
    displayName: Java CI CD Build Pipeline
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      displayName: CodeCheckout
    - task: Maven@3
      displayName: BuildWithMaven
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        publishJUnitResults: false
    - task: Maven@3
      displayName: UnitTest
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Maven@3
      displayName: Sonarqube CodeScan
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'sonar:sonar'
        options: '-Dsonar.host.url=http://rs06ue2dguidingstars-rg02-sonarqube.eastus.azurecontainer.io:9000  -Dsonar.login=e92ce9972d34514b092388c1a60fc5c2834dce85 -Donar.sources=. -Dsonar.java.binaries=. -Dsonar.java.coveragePlugin=jacoco -DsonarJavaSource=. -Dsonar.junit.reportsPath=target/surefire-reports -Dsonar.surefire.reportsPath=target/surefire-reports -Dsonar.jacoco.reportPath=target/jacoco.exec -Dsonar.binaries=target/classes'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Maven@3
      displayName: SeleniumTest
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'verify'
        options: '-P tomcat90'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
  #  - task: UniversalPackages@0
  #    displayName: PublishArtifacts
  #    inputs:
  #      command: 'publish'
  #      publishDirectory: $(artifactsPath)
  #      feedsToUsePublish: 'internal'
  #      vstsFeedPublish: $(azureFeedPublishName)
  #      vstsFeedPackagePublish: $(azureArtifactName)
  #      versionOption: 'patch'
  #  - task: AzureWebApp@1
  #    displayName: App Deployment
  #    inputs:
  #      azureSubscription: $(azureServiceConnectionId)
  #      appType: 'webAppLinux'
  #      appName: $(webServer)
  #      package: $(artifactsPath)